services:
  php-apache:
    build:
      context: ./php
    container_name: php-apache
    platform: linux/amd64
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - "${PHP_PORT:-8000}:80"
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  db:
    image: mariadb:10.5
    container_name: db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT:-9906}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
